/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as BrugereRouteImport } from './routes/brugere'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as LmuIndexRouteImport } from './routes/lmu.index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams.$teamId'
import { Route as LmuTeamsRouteImport } from './routes/lmu.teams'
import { Route as LmuLigaRouteImport } from './routes/lmu.liga'
import { Route as LigaerLeagueIdRouteImport } from './routes/ligaer.$leagueId'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated.profil'
import { Route as AuthenticatedMineProtestsRouteImport } from './routes/_authenticated.mine-protests'
import { Route as AuthenticatedArkivRouteImport } from './routes/_authenticated.arkiv'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as LigaerLeagueIdIndexRouteImport } from './routes/ligaer.$leagueId.index'
import { Route as LigaerLeagueIdReglerRouteImport } from './routes/ligaer.$leagueId.regler'
import { Route as ApiPublicLeaderboardUploadRouteImport } from './routes/api/public/leaderboard-upload'
import { Route as AuthenticatedProfilUserIdRouteImport } from './routes/_authenticated.profil.$userId'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated._admin.admin.index'
import { Route as LigaerLeagueIdAfdelingDivisionIdRouteImport } from './routes/ligaer.$leagueId.afdeling.$divisionId'
import { Route as ApiPublicDownloadCompanionRouteImport } from './routes/api/public/download/companion'
import { Route as ApiPublicCompanionVerifyTokenRouteImport } from './routes/api/public/companion/verify-token'
import { Route as AuthenticatedAdminAdminProtestsRouteImport } from './routes/_authenticated._admin.admin.protests'
import { Route as AuthenticatedAdminAdminLigaerRouteImport } from './routes/_authenticated._admin.admin.ligaer'
import { Route as AuthenticatedAdminAdminBrugereRouteImport } from './routes/_authenticated._admin.admin.brugere'
import { Route as AuthenticatedAdminAdminAfventerRouteImport } from './routes/_authenticated._admin.admin.afventer'
import { Route as AuthenticatedAdminAdminProtestsIndexRouteImport } from './routes/_authenticated._admin.admin.protests.index'
import { Route as AuthenticatedAdminAdminProtestsProtestIdRouteImport } from './routes/_authenticated._admin.admin.protests.$protestId'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdStillingerRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.stillinger'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdReglerRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.regler'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdEntriesRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.entries'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.afdelinger'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BrugereRoute = BrugereRouteImport.update({
  id: '/brugere',
  path: '/brugere',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const LmuIndexRoute = LmuIndexRouteImport.update({
  id: '/lmu/',
  path: '/lmu/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const LmuTeamsRoute = LmuTeamsRouteImport.update({
  id: '/lmu/teams',
  path: '/lmu/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const LmuLigaRoute = LmuLigaRouteImport.update({
  id: '/lmu/liga',
  path: '/lmu/liga',
  getParentRoute: () => rootRouteImport,
} as any)
const LigaerLeagueIdRoute = LigaerLeagueIdRouteImport.update({
  id: '/ligaer/$leagueId',
  path: '/ligaer/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMineProtestsRoute =
  AuthenticatedMineProtestsRouteImport.update({
    id: '/mine-protests',
    path: '/mine-protests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedArkivRoute = AuthenticatedArkivRouteImport.update({
  id: '/arkiv',
  path: '/arkiv',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LigaerLeagueIdIndexRoute = LigaerLeagueIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LigaerLeagueIdRoute,
} as any)
const LigaerLeagueIdReglerRoute = LigaerLeagueIdReglerRouteImport.update({
  id: '/regler',
  path: '/regler',
  getParentRoute: () => LigaerLeagueIdRoute,
} as any)
const ApiPublicLeaderboardUploadRoute =
  ApiPublicLeaderboardUploadRouteImport.update({
    id: '/api/public/leaderboard-upload',
    path: '/api/public/leaderboard-upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedProfilUserIdRoute =
  AuthenticatedProfilUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedProfilRoute,
  } as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LigaerLeagueIdAfdelingDivisionIdRoute =
  LigaerLeagueIdAfdelingDivisionIdRouteImport.update({
    id: '/afdeling/$divisionId',
    path: '/afdeling/$divisionId',
    getParentRoute: () => LigaerLeagueIdRoute,
  } as any)
const ApiPublicDownloadCompanionRoute =
  ApiPublicDownloadCompanionRouteImport.update({
    id: '/api/public/download/companion',
    path: '/api/public/download/companion',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCompanionVerifyTokenRoute =
  ApiPublicCompanionVerifyTokenRouteImport.update({
    id: '/api/public/companion/verify-token',
    path: '/api/public/companion/verify-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminAdminProtestsRoute =
  AuthenticatedAdminAdminProtestsRouteImport.update({
    id: '/admin/protests',
    path: '/admin/protests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminLigaerRoute =
  AuthenticatedAdminAdminLigaerRouteImport.update({
    id: '/admin/ligaer',
    path: '/admin/ligaer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminBrugereRoute =
  AuthenticatedAdminAdminBrugereRouteImport.update({
    id: '/admin/brugere',
    path: '/admin/brugere',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminAfventerRoute =
  AuthenticatedAdminAdminAfventerRouteImport.update({
    id: '/admin/afventer',
    path: '/admin/afventer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminProtestsIndexRoute =
  AuthenticatedAdminAdminProtestsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminProtestsRoute,
  } as any)
const AuthenticatedAdminAdminProtestsProtestIdRoute =
  AuthenticatedAdminAdminProtestsProtestIdRouteImport.update({
    id: '/$protestId',
    path: '/$protestId',
    getParentRoute: () => AuthenticatedAdminAdminProtestsRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute =
  AuthenticatedAdminAdminLigaerLeagueIdStillingerRouteImport.update({
    id: '/$leagueId/stillinger',
    path: '/$leagueId/stillinger',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdReglerRoute =
  AuthenticatedAdminAdminLigaerLeagueIdReglerRouteImport.update({
    id: '/$leagueId/regler',
    path: '/$leagueId/regler',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute =
  AuthenticatedAdminAdminLigaerLeagueIdEntriesRouteImport.update({
    id: '/$leagueId/entries',
    path: '/$leagueId/entries',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute =
  AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRouteImport.update({
    id: '/$leagueId/afdelinger',
    path: '/$leagueId/afdelinger',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brugere': typeof BrugereRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/arkiv': typeof AuthenticatedArkivRoute
  '/mine-protests': typeof AuthenticatedMineProtestsRoute
  '/profil': typeof AuthenticatedProfilRouteWithChildren
  '/ligaer/$leagueId': typeof LigaerLeagueIdRouteWithChildren
  '/lmu/liga': typeof LmuLigaRoute
  '/lmu/teams': typeof LmuTeamsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/lmu/': typeof LmuIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/profil/$userId': typeof AuthenticatedProfilUserIdRoute
  '/api/public/leaderboard-upload': typeof ApiPublicLeaderboardUploadRoute
  '/ligaer/$leagueId/regler': typeof LigaerLeagueIdReglerRoute
  '/ligaer/$leagueId/': typeof LigaerLeagueIdIndexRoute
  '/admin/afventer': typeof AuthenticatedAdminAdminAfventerRoute
  '/admin/brugere': typeof AuthenticatedAdminAdminBrugereRoute
  '/admin/ligaer': typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  '/admin/protests': typeof AuthenticatedAdminAdminProtestsRouteWithChildren
  '/api/public/companion/verify-token': typeof ApiPublicCompanionVerifyTokenRoute
  '/api/public/download/companion': typeof ApiPublicDownloadCompanionRoute
  '/ligaer/$leagueId/afdeling/$divisionId': typeof LigaerLeagueIdAfdelingDivisionIdRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/protests/$protestId': typeof AuthenticatedAdminAdminProtestsProtestIdRoute
  '/admin/protests/': typeof AuthenticatedAdminAdminProtestsIndexRoute
  '/admin/ligaer/$leagueId/afdelinger': typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  '/admin/ligaer/$leagueId/entries': typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  '/admin/ligaer/$leagueId/regler': typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  '/admin/ligaer/$leagueId/stillinger': typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brugere': typeof BrugereRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/arkiv': typeof AuthenticatedArkivRoute
  '/mine-protests': typeof AuthenticatedMineProtestsRoute
  '/profil': typeof AuthenticatedProfilRouteWithChildren
  '/lmu/liga': typeof LmuLigaRoute
  '/lmu/teams': typeof LmuTeamsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/lmu': typeof LmuIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/profil/$userId': typeof AuthenticatedProfilUserIdRoute
  '/api/public/leaderboard-upload': typeof ApiPublicLeaderboardUploadRoute
  '/ligaer/$leagueId/regler': typeof LigaerLeagueIdReglerRoute
  '/ligaer/$leagueId': typeof LigaerLeagueIdIndexRoute
  '/admin/afventer': typeof AuthenticatedAdminAdminAfventerRoute
  '/admin/brugere': typeof AuthenticatedAdminAdminBrugereRoute
  '/admin/ligaer': typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  '/api/public/companion/verify-token': typeof ApiPublicCompanionVerifyTokenRoute
  '/api/public/download/companion': typeof ApiPublicDownloadCompanionRoute
  '/ligaer/$leagueId/afdeling/$divisionId': typeof LigaerLeagueIdAfdelingDivisionIdRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/protests/$protestId': typeof AuthenticatedAdminAdminProtestsProtestIdRoute
  '/admin/protests': typeof AuthenticatedAdminAdminProtestsIndexRoute
  '/admin/ligaer/$leagueId/afdelinger': typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  '/admin/ligaer/$leagueId/entries': typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  '/admin/ligaer/$leagueId/regler': typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  '/admin/ligaer/$leagueId/stillinger': typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/brugere': typeof BrugereRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/arkiv': typeof AuthenticatedArkivRoute
  '/_authenticated/mine-protests': typeof AuthenticatedMineProtestsRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRouteWithChildren
  '/ligaer/$leagueId': typeof LigaerLeagueIdRouteWithChildren
  '/lmu/liga': typeof LmuLigaRoute
  '/lmu/teams': typeof LmuTeamsRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/lmu/': typeof LmuIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/_authenticated/profil/$userId': typeof AuthenticatedProfilUserIdRoute
  '/api/public/leaderboard-upload': typeof ApiPublicLeaderboardUploadRoute
  '/ligaer/$leagueId/regler': typeof LigaerLeagueIdReglerRoute
  '/ligaer/$leagueId/': typeof LigaerLeagueIdIndexRoute
  '/_authenticated/_admin/admin/afventer': typeof AuthenticatedAdminAdminAfventerRoute
  '/_authenticated/_admin/admin/brugere': typeof AuthenticatedAdminAdminBrugereRoute
  '/_authenticated/_admin/admin/ligaer': typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  '/_authenticated/_admin/admin/protests': typeof AuthenticatedAdminAdminProtestsRouteWithChildren
  '/api/public/companion/verify-token': typeof ApiPublicCompanionVerifyTokenRoute
  '/api/public/download/companion': typeof ApiPublicDownloadCompanionRoute
  '/ligaer/$leagueId/afdeling/$divisionId': typeof LigaerLeagueIdAfdelingDivisionIdRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/protests/$protestId': typeof AuthenticatedAdminAdminProtestsProtestIdRoute
  '/_authenticated/_admin/admin/protests/': typeof AuthenticatedAdminAdminProtestsIndexRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger': typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/entries': typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/regler': typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger': typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brugere'
    | '/leaderboard'
    | '/login'
    | '/sitemap.xml'
    | '/arkiv'
    | '/mine-protests'
    | '/profil'
    | '/ligaer/$leagueId'
    | '/lmu/liga'
    | '/lmu/teams'
    | '/teams/$teamId'
    | '/lmu/'
    | '/teams/'
    | '/profil/$userId'
    | '/api/public/leaderboard-upload'
    | '/ligaer/$leagueId/regler'
    | '/ligaer/$leagueId/'
    | '/admin/afventer'
    | '/admin/brugere'
    | '/admin/ligaer'
    | '/admin/protests'
    | '/api/public/companion/verify-token'
    | '/api/public/download/companion'
    | '/ligaer/$leagueId/afdeling/$divisionId'
    | '/admin/'
    | '/admin/protests/$protestId'
    | '/admin/protests/'
    | '/admin/ligaer/$leagueId/afdelinger'
    | '/admin/ligaer/$leagueId/entries'
    | '/admin/ligaer/$leagueId/regler'
    | '/admin/ligaer/$leagueId/stillinger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brugere'
    | '/leaderboard'
    | '/login'
    | '/sitemap.xml'
    | '/arkiv'
    | '/mine-protests'
    | '/profil'
    | '/lmu/liga'
    | '/lmu/teams'
    | '/teams/$teamId'
    | '/lmu'
    | '/teams'
    | '/profil/$userId'
    | '/api/public/leaderboard-upload'
    | '/ligaer/$leagueId/regler'
    | '/ligaer/$leagueId'
    | '/admin/afventer'
    | '/admin/brugere'
    | '/admin/ligaer'
    | '/api/public/companion/verify-token'
    | '/api/public/download/companion'
    | '/ligaer/$leagueId/afdeling/$divisionId'
    | '/admin'
    | '/admin/protests/$protestId'
    | '/admin/protests'
    | '/admin/ligaer/$leagueId/afdelinger'
    | '/admin/ligaer/$leagueId/entries'
    | '/admin/ligaer/$leagueId/regler'
    | '/admin/ligaer/$leagueId/stillinger'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/brugere'
    | '/leaderboard'
    | '/login'
    | '/sitemap.xml'
    | '/_authenticated/_admin'
    | '/_authenticated/arkiv'
    | '/_authenticated/mine-protests'
    | '/_authenticated/profil'
    | '/ligaer/$leagueId'
    | '/lmu/liga'
    | '/lmu/teams'
    | '/teams/$teamId'
    | '/lmu/'
    | '/teams/'
    | '/_authenticated/profil/$userId'
    | '/api/public/leaderboard-upload'
    | '/ligaer/$leagueId/regler'
    | '/ligaer/$leagueId/'
    | '/_authenticated/_admin/admin/afventer'
    | '/_authenticated/_admin/admin/brugere'
    | '/_authenticated/_admin/admin/ligaer'
    | '/_authenticated/_admin/admin/protests'
    | '/api/public/companion/verify-token'
    | '/api/public/download/companion'
    | '/ligaer/$leagueId/afdeling/$divisionId'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/protests/$protestId'
    | '/_authenticated/_admin/admin/protests/'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/entries'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/regler'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BrugereRoute: typeof BrugereRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LigaerLeagueIdRoute: typeof LigaerLeagueIdRouteWithChildren
  LmuLigaRoute: typeof LmuLigaRoute
  LmuTeamsRoute: typeof LmuTeamsRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  LmuIndexRoute: typeof LmuIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
  ApiPublicLeaderboardUploadRoute: typeof ApiPublicLeaderboardUploadRoute
  ApiPublicCompanionVerifyTokenRoute: typeof ApiPublicCompanionVerifyTokenRoute
  ApiPublicDownloadCompanionRoute: typeof ApiPublicDownloadCompanionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brugere': {
      id: '/brugere'
      path: '/brugere'
      fullPath: '/brugere'
      preLoaderRoute: typeof BrugereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lmu/': {
      id: '/lmu/'
      path: '/lmu'
      fullPath: '/lmu/'
      preLoaderRoute: typeof LmuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lmu/teams': {
      id: '/lmu/teams'
      path: '/lmu/teams'
      fullPath: '/lmu/teams'
      preLoaderRoute: typeof LmuTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lmu/liga': {
      id: '/lmu/liga'
      path: '/lmu/liga'
      fullPath: '/lmu/liga'
      preLoaderRoute: typeof LmuLigaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligaer/$leagueId': {
      id: '/ligaer/$leagueId'
      path: '/ligaer/$leagueId'
      fullPath: '/ligaer/$leagueId'
      preLoaderRoute: typeof LigaerLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mine-protests': {
      id: '/_authenticated/mine-protests'
      path: '/mine-protests'
      fullPath: '/mine-protests'
      preLoaderRoute: typeof AuthenticatedMineProtestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arkiv': {
      id: '/_authenticated/arkiv'
      path: '/arkiv'
      fullPath: '/arkiv'
      preLoaderRoute: typeof AuthenticatedArkivRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/ligaer/$leagueId/': {
      id: '/ligaer/$leagueId/'
      path: '/'
      fullPath: '/ligaer/$leagueId/'
      preLoaderRoute: typeof LigaerLeagueIdIndexRouteImport
      parentRoute: typeof LigaerLeagueIdRoute
    }
    '/ligaer/$leagueId/regler': {
      id: '/ligaer/$leagueId/regler'
      path: '/regler'
      fullPath: '/ligaer/$leagueId/regler'
      preLoaderRoute: typeof LigaerLeagueIdReglerRouteImport
      parentRoute: typeof LigaerLeagueIdRoute
    }
    '/api/public/leaderboard-upload': {
      id: '/api/public/leaderboard-upload'
      path: '/api/public/leaderboard-upload'
      fullPath: '/api/public/leaderboard-upload'
      preLoaderRoute: typeof ApiPublicLeaderboardUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profil/$userId': {
      id: '/_authenticated/profil/$userId'
      path: '/$userId'
      fullPath: '/profil/$userId'
      preLoaderRoute: typeof AuthenticatedProfilUserIdRouteImport
      parentRoute: typeof AuthenticatedProfilRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/ligaer/$leagueId/afdeling/$divisionId': {
      id: '/ligaer/$leagueId/afdeling/$divisionId'
      path: '/afdeling/$divisionId'
      fullPath: '/ligaer/$leagueId/afdeling/$divisionId'
      preLoaderRoute: typeof LigaerLeagueIdAfdelingDivisionIdRouteImport
      parentRoute: typeof LigaerLeagueIdRoute
    }
    '/api/public/download/companion': {
      id: '/api/public/download/companion'
      path: '/api/public/download/companion'
      fullPath: '/api/public/download/companion'
      preLoaderRoute: typeof ApiPublicDownloadCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/companion/verify-token': {
      id: '/api/public/companion/verify-token'
      path: '/api/public/companion/verify-token'
      fullPath: '/api/public/companion/verify-token'
      preLoaderRoute: typeof ApiPublicCompanionVerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/protests': {
      id: '/_authenticated/_admin/admin/protests'
      path: '/admin/protests'
      fullPath: '/admin/protests'
      preLoaderRoute: typeof AuthenticatedAdminAdminProtestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ligaer': {
      id: '/_authenticated/_admin/admin/ligaer'
      path: '/admin/ligaer'
      fullPath: '/admin/ligaer'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/brugere': {
      id: '/_authenticated/_admin/admin/brugere'
      path: '/admin/brugere'
      fullPath: '/admin/brugere'
      preLoaderRoute: typeof AuthenticatedAdminAdminBrugereRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/afventer': {
      id: '/_authenticated/_admin/admin/afventer'
      path: '/admin/afventer'
      fullPath: '/admin/afventer'
      preLoaderRoute: typeof AuthenticatedAdminAdminAfventerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/protests/': {
      id: '/_authenticated/_admin/admin/protests/'
      path: '/'
      fullPath: '/admin/protests/'
      preLoaderRoute: typeof AuthenticatedAdminAdminProtestsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminProtestsRoute
    }
    '/_authenticated/_admin/admin/protests/$protestId': {
      id: '/_authenticated/_admin/admin/protests/$protestId'
      path: '/$protestId'
      fullPath: '/admin/protests/$protestId'
      preLoaderRoute: typeof AuthenticatedAdminAdminProtestsProtestIdRouteImport
      parentRoute: typeof AuthenticatedAdminAdminProtestsRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger'
      path: '/$leagueId/stillinger'
      fullPath: '/admin/ligaer/$leagueId/stillinger'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/regler': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/regler'
      path: '/$leagueId/regler'
      fullPath: '/admin/ligaer/$leagueId/regler'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/entries': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/entries'
      path: '/$leagueId/entries'
      fullPath: '/admin/ligaer/$leagueId/entries'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger'
      path: '/$leagueId/afdelinger'
      fullPath: '/admin/ligaer/$leagueId/afdelinger'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
  }
}

interface AuthenticatedAdminAdminLigaerRouteChildren {
  AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  AuthenticatedAdminAdminLigaerLeagueIdReglerRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}

const AuthenticatedAdminAdminLigaerRouteChildren: AuthenticatedAdminAdminLigaerRouteChildren =
  {
    AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute:
      AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute,
    AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute:
      AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute,
    AuthenticatedAdminAdminLigaerLeagueIdReglerRoute:
      AuthenticatedAdminAdminLigaerLeagueIdReglerRoute,
    AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute:
      AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute,
  }

const AuthenticatedAdminAdminLigaerRouteWithChildren =
  AuthenticatedAdminAdminLigaerRoute._addFileChildren(
    AuthenticatedAdminAdminLigaerRouteChildren,
  )

interface AuthenticatedAdminAdminProtestsRouteChildren {
  AuthenticatedAdminAdminProtestsProtestIdRoute: typeof AuthenticatedAdminAdminProtestsProtestIdRoute
  AuthenticatedAdminAdminProtestsIndexRoute: typeof AuthenticatedAdminAdminProtestsIndexRoute
}

const AuthenticatedAdminAdminProtestsRouteChildren: AuthenticatedAdminAdminProtestsRouteChildren =
  {
    AuthenticatedAdminAdminProtestsProtestIdRoute:
      AuthenticatedAdminAdminProtestsProtestIdRoute,
    AuthenticatedAdminAdminProtestsIndexRoute:
      AuthenticatedAdminAdminProtestsIndexRoute,
  }

const AuthenticatedAdminAdminProtestsRouteWithChildren =
  AuthenticatedAdminAdminProtestsRoute._addFileChildren(
    AuthenticatedAdminAdminProtestsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminAfventerRoute: typeof AuthenticatedAdminAdminAfventerRoute
  AuthenticatedAdminAdminBrugereRoute: typeof AuthenticatedAdminAdminBrugereRoute
  AuthenticatedAdminAdminLigaerRoute: typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  AuthenticatedAdminAdminProtestsRoute: typeof AuthenticatedAdminAdminProtestsRouteWithChildren
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminAfventerRoute: AuthenticatedAdminAdminAfventerRoute,
  AuthenticatedAdminAdminBrugereRoute: AuthenticatedAdminAdminBrugereRoute,
  AuthenticatedAdminAdminLigaerRoute:
    AuthenticatedAdminAdminLigaerRouteWithChildren,
  AuthenticatedAdminAdminProtestsRoute:
    AuthenticatedAdminAdminProtestsRouteWithChildren,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedProfilRouteChildren {
  AuthenticatedProfilUserIdRoute: typeof AuthenticatedProfilUserIdRoute
}

const AuthenticatedProfilRouteChildren: AuthenticatedProfilRouteChildren = {
  AuthenticatedProfilUserIdRoute: AuthenticatedProfilUserIdRoute,
}

const AuthenticatedProfilRouteWithChildren =
  AuthenticatedProfilRoute._addFileChildren(AuthenticatedProfilRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedArkivRoute: typeof AuthenticatedArkivRoute
  AuthenticatedMineProtestsRoute: typeof AuthenticatedMineProtestsRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedArkivRoute: AuthenticatedArkivRoute,
  AuthenticatedMineProtestsRoute: AuthenticatedMineProtestsRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LigaerLeagueIdRouteChildren {
  LigaerLeagueIdReglerRoute: typeof LigaerLeagueIdReglerRoute
  LigaerLeagueIdIndexRoute: typeof LigaerLeagueIdIndexRoute
  LigaerLeagueIdAfdelingDivisionIdRoute: typeof LigaerLeagueIdAfdelingDivisionIdRoute
}

const LigaerLeagueIdRouteChildren: LigaerLeagueIdRouteChildren = {
  LigaerLeagueIdReglerRoute: LigaerLeagueIdReglerRoute,
  LigaerLeagueIdIndexRoute: LigaerLeagueIdIndexRoute,
  LigaerLeagueIdAfdelingDivisionIdRoute: LigaerLeagueIdAfdelingDivisionIdRoute,
}

const LigaerLeagueIdRouteWithChildren = LigaerLeagueIdRoute._addFileChildren(
  LigaerLeagueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BrugereRoute: BrugereRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LigaerLeagueIdRoute: LigaerLeagueIdRouteWithChildren,
  LmuLigaRoute: LmuLigaRoute,
  LmuTeamsRoute: LmuTeamsRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  LmuIndexRoute: LmuIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
  ApiPublicLeaderboardUploadRoute: ApiPublicLeaderboardUploadRoute,
  ApiPublicCompanionVerifyTokenRoute: ApiPublicCompanionVerifyTokenRoute,
  ApiPublicDownloadCompanionRoute: ApiPublicDownloadCompanionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
