/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LigaerLeagueIdRouteImport } from './routes/ligaer.$leagueId'
import { Route as AuthenticatedMineProtestsRouteImport } from './routes/_authenticated.mine-protests'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated._admin'
import { Route as LigaerLeagueIdReglerRouteImport } from './routes/ligaer.$leagueId.regler'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated._admin.admin.index'
import { Route as LigaerLeagueIdAfdelingDivisionIdRouteImport } from './routes/ligaer.$leagueId.afdeling.$divisionId'
import { Route as AuthenticatedAdminAdminProtestsRouteImport } from './routes/_authenticated._admin.admin.protests'
import { Route as AuthenticatedAdminAdminLigaerRouteImport } from './routes/_authenticated._admin.admin.ligaer'
import { Route as AuthenticatedAdminAdminBrugereRouteImport } from './routes/_authenticated._admin.admin.brugere'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdStillingerRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.stillinger'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdReglerRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.regler'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdEntriesRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.entries'
import { Route as AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRouteImport } from './routes/_authenticated._admin.admin.ligaer.$leagueId.afdelinger'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LigaerLeagueIdRoute = LigaerLeagueIdRouteImport.update({
  id: '/ligaer/$leagueId',
  path: '/ligaer/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMineProtestsRoute =
  AuthenticatedMineProtestsRouteImport.update({
    id: '/mine-protests',
    path: '/mine-protests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LigaerLeagueIdReglerRoute = LigaerLeagueIdReglerRouteImport.update({
  id: '/regler',
  path: '/regler',
  getParentRoute: () => LigaerLeagueIdRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LigaerLeagueIdAfdelingDivisionIdRoute =
  LigaerLeagueIdAfdelingDivisionIdRouteImport.update({
    id: '/afdeling/$divisionId',
    path: '/afdeling/$divisionId',
    getParentRoute: () => LigaerLeagueIdRoute,
  } as any)
const AuthenticatedAdminAdminProtestsRoute =
  AuthenticatedAdminAdminProtestsRouteImport.update({
    id: '/admin/protests',
    path: '/admin/protests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminLigaerRoute =
  AuthenticatedAdminAdminLigaerRouteImport.update({
    id: '/admin/ligaer',
    path: '/admin/ligaer',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminBrugereRoute =
  AuthenticatedAdminAdminBrugereRouteImport.update({
    id: '/admin/brugere',
    path: '/admin/brugere',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute =
  AuthenticatedAdminAdminLigaerLeagueIdStillingerRouteImport.update({
    id: '/$leagueId/stillinger',
    path: '/$leagueId/stillinger',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdReglerRoute =
  AuthenticatedAdminAdminLigaerLeagueIdReglerRouteImport.update({
    id: '/$leagueId/regler',
    path: '/$leagueId/regler',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute =
  AuthenticatedAdminAdminLigaerLeagueIdEntriesRouteImport.update({
    id: '/$leagueId/entries',
    path: '/$leagueId/entries',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)
const AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute =
  AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRouteImport.update({
    id: '/$leagueId/afdelinger',
    path: '/$leagueId/afdelinger',
    getParentRoute: () => AuthenticatedAdminAdminLigaerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mine-protests': typeof AuthenticatedMineProtestsRoute
  '/ligaer/$leagueId': typeof LigaerLeagueIdRouteWithChildren
  '/ligaer/$leagueId/regler': typeof LigaerLeagueIdReglerRoute
  '/admin/brugere': typeof AuthenticatedAdminAdminBrugereRoute
  '/admin/ligaer': typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  '/admin/protests': typeof AuthenticatedAdminAdminProtestsRoute
  '/ligaer/$leagueId/afdeling/$divisionId': typeof LigaerLeagueIdAfdelingDivisionIdRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/ligaer/$leagueId/afdelinger': typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  '/admin/ligaer/$leagueId/entries': typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  '/admin/ligaer/$leagueId/regler': typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  '/admin/ligaer/$leagueId/stillinger': typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mine-protests': typeof AuthenticatedMineProtestsRoute
  '/ligaer/$leagueId': typeof LigaerLeagueIdRouteWithChildren
  '/ligaer/$leagueId/regler': typeof LigaerLeagueIdReglerRoute
  '/admin/brugere': typeof AuthenticatedAdminAdminBrugereRoute
  '/admin/ligaer': typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  '/admin/protests': typeof AuthenticatedAdminAdminProtestsRoute
  '/ligaer/$leagueId/afdeling/$divisionId': typeof LigaerLeagueIdAfdelingDivisionIdRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
  '/admin/ligaer/$leagueId/afdelinger': typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  '/admin/ligaer/$leagueId/entries': typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  '/admin/ligaer/$leagueId/regler': typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  '/admin/ligaer/$leagueId/stillinger': typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/mine-protests': typeof AuthenticatedMineProtestsRoute
  '/ligaer/$leagueId': typeof LigaerLeagueIdRouteWithChildren
  '/ligaer/$leagueId/regler': typeof LigaerLeagueIdReglerRoute
  '/_authenticated/_admin/admin/brugere': typeof AuthenticatedAdminAdminBrugereRoute
  '/_authenticated/_admin/admin/ligaer': typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  '/_authenticated/_admin/admin/protests': typeof AuthenticatedAdminAdminProtestsRoute
  '/ligaer/$leagueId/afdeling/$divisionId': typeof LigaerLeagueIdAfdelingDivisionIdRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger': typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/entries': typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/regler': typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger': typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/mine-protests'
    | '/ligaer/$leagueId'
    | '/ligaer/$leagueId/regler'
    | '/admin/brugere'
    | '/admin/ligaer'
    | '/admin/protests'
    | '/ligaer/$leagueId/afdeling/$divisionId'
    | '/admin/'
    | '/admin/ligaer/$leagueId/afdelinger'
    | '/admin/ligaer/$leagueId/entries'
    | '/admin/ligaer/$leagueId/regler'
    | '/admin/ligaer/$leagueId/stillinger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mine-protests'
    | '/ligaer/$leagueId'
    | '/ligaer/$leagueId/regler'
    | '/admin/brugere'
    | '/admin/ligaer'
    | '/admin/protests'
    | '/ligaer/$leagueId/afdeling/$divisionId'
    | '/admin'
    | '/admin/ligaer/$leagueId/afdelinger'
    | '/admin/ligaer/$leagueId/entries'
    | '/admin/ligaer/$leagueId/regler'
    | '/admin/ligaer/$leagueId/stillinger'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_admin'
    | '/_authenticated/mine-protests'
    | '/ligaer/$leagueId'
    | '/ligaer/$leagueId/regler'
    | '/_authenticated/_admin/admin/brugere'
    | '/_authenticated/_admin/admin/ligaer'
    | '/_authenticated/_admin/admin/protests'
    | '/ligaer/$leagueId/afdeling/$divisionId'
    | '/_authenticated/_admin/admin/'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/entries'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/regler'
    | '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LigaerLeagueIdRoute: typeof LigaerLeagueIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligaer/$leagueId': {
      id: '/ligaer/$leagueId'
      path: '/ligaer/$leagueId'
      fullPath: '/ligaer/$leagueId'
      preLoaderRoute: typeof LigaerLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mine-protests': {
      id: '/_authenticated/mine-protests'
      path: '/mine-protests'
      fullPath: '/mine-protests'
      preLoaderRoute: typeof AuthenticatedMineProtestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/ligaer/$leagueId/regler': {
      id: '/ligaer/$leagueId/regler'
      path: '/regler'
      fullPath: '/ligaer/$leagueId/regler'
      preLoaderRoute: typeof LigaerLeagueIdReglerRouteImport
      parentRoute: typeof LigaerLeagueIdRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/ligaer/$leagueId/afdeling/$divisionId': {
      id: '/ligaer/$leagueId/afdeling/$divisionId'
      path: '/afdeling/$divisionId'
      fullPath: '/ligaer/$leagueId/afdeling/$divisionId'
      preLoaderRoute: typeof LigaerLeagueIdAfdelingDivisionIdRouteImport
      parentRoute: typeof LigaerLeagueIdRoute
    }
    '/_authenticated/_admin/admin/protests': {
      id: '/_authenticated/_admin/admin/protests'
      path: '/admin/protests'
      fullPath: '/admin/protests'
      preLoaderRoute: typeof AuthenticatedAdminAdminProtestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ligaer': {
      id: '/_authenticated/_admin/admin/ligaer'
      path: '/admin/ligaer'
      fullPath: '/admin/ligaer'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/brugere': {
      id: '/_authenticated/_admin/admin/brugere'
      path: '/admin/brugere'
      fullPath: '/admin/brugere'
      preLoaderRoute: typeof AuthenticatedAdminAdminBrugereRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/stillinger'
      path: '/$leagueId/stillinger'
      fullPath: '/admin/ligaer/$leagueId/stillinger'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/regler': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/regler'
      path: '/$leagueId/regler'
      fullPath: '/admin/ligaer/$leagueId/regler'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/entries': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/entries'
      path: '/$leagueId/entries'
      fullPath: '/admin/ligaer/$leagueId/entries'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
    '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger': {
      id: '/_authenticated/_admin/admin/ligaer/$leagueId/afdelinger'
      path: '/$leagueId/afdelinger'
      fullPath: '/admin/ligaer/$leagueId/afdelinger'
      preLoaderRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRouteImport
      parentRoute: typeof AuthenticatedAdminAdminLigaerRoute
    }
  }
}

interface AuthenticatedAdminAdminLigaerRouteChildren {
  AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute
  AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute
  AuthenticatedAdminAdminLigaerLeagueIdReglerRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdReglerRoute
  AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute: typeof AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute
}

const AuthenticatedAdminAdminLigaerRouteChildren: AuthenticatedAdminAdminLigaerRouteChildren =
  {
    AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute:
      AuthenticatedAdminAdminLigaerLeagueIdAfdelingerRoute,
    AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute:
      AuthenticatedAdminAdminLigaerLeagueIdEntriesRoute,
    AuthenticatedAdminAdminLigaerLeagueIdReglerRoute:
      AuthenticatedAdminAdminLigaerLeagueIdReglerRoute,
    AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute:
      AuthenticatedAdminAdminLigaerLeagueIdStillingerRoute,
  }

const AuthenticatedAdminAdminLigaerRouteWithChildren =
  AuthenticatedAdminAdminLigaerRoute._addFileChildren(
    AuthenticatedAdminAdminLigaerRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminBrugereRoute: typeof AuthenticatedAdminAdminBrugereRoute
  AuthenticatedAdminAdminLigaerRoute: typeof AuthenticatedAdminAdminLigaerRouteWithChildren
  AuthenticatedAdminAdminProtestsRoute: typeof AuthenticatedAdminAdminProtestsRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminBrugereRoute: AuthenticatedAdminAdminBrugereRoute,
  AuthenticatedAdminAdminLigaerRoute:
    AuthenticatedAdminAdminLigaerRouteWithChildren,
  AuthenticatedAdminAdminProtestsRoute: AuthenticatedAdminAdminProtestsRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMineProtestsRoute: typeof AuthenticatedMineProtestsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMineProtestsRoute: AuthenticatedMineProtestsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface LigaerLeagueIdRouteChildren {
  LigaerLeagueIdReglerRoute: typeof LigaerLeagueIdReglerRoute
  LigaerLeagueIdAfdelingDivisionIdRoute: typeof LigaerLeagueIdAfdelingDivisionIdRoute
}

const LigaerLeagueIdRouteChildren: LigaerLeagueIdRouteChildren = {
  LigaerLeagueIdReglerRoute: LigaerLeagueIdReglerRoute,
  LigaerLeagueIdAfdelingDivisionIdRoute: LigaerLeagueIdAfdelingDivisionIdRoute,
}

const LigaerLeagueIdRouteWithChildren = LigaerLeagueIdRoute._addFileChildren(
  LigaerLeagueIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  LigaerLeagueIdRoute: LigaerLeagueIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
